apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ylsj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0039-tenant/tkrw-pr712-0075-0039-app/devfile-sample-ylsj@sha256:e84a3ba27d3812b480778f393045ffbfbbc425c48a62a4bdc4cc4e3a48bdf7e1
        name: my-nodejs
        resources: {}
status: {}
